### ISSUE TITLE
Build failure on Mageia (Cauldron) with new 16.01 release against Qt 5.6.0

### ISSUE THREAD

**Issue by david-geiger** [mltframework/shotcut#180]
Hello,

I tried to compile shotcut-16.01 against Qt5-5.6.0 (beta) but I get an error:

In file included from widgets/scopes/scopewidget.cpp:19:0:
widgets/scopes/scopewidget.h:87:10: error: 'void ScopeWidget::onNewFrame(const SharedFrame&)' marked 'final', but is not virtual
     void onNewFrame(const SharedFrame& frame) Q_DECL_FINAL;

Full compile log:
http://pastebin.com/TmT5eYAi

Regards,
David

**Comment by metellius** [comment]
That's because you're compiling with c++11 (and also a version of qt not supported), which is not currently in use in shotcut. Indeed, in this case it does not make sense that onNewFrame is final when it is not virtual, but I'm also betting that there will be more compile errors like this one with c++11 turned on. I'm guessing c++11 has not been enabled yet for compiler compatability reasons, but @ddennedy will have to confirm that.

**Comment by ddennedy** [comment]
You are on your own with custom builds.

**Comment by akien-mga** [comment]
Nice way to handle official packagers that try to bring your application to the public...

**Comment by metellius** [comment]
Lack of official distro packaging resurfaces now and then, see #26 for a recent discussion.

**Comment by ddennedy** [comment]
I don't like distro packages for my app. This comes from someone with 15 years experience making software for desktop Linux. So, I know what the fuck I'm talking about.

**Comment by bmatherly** [comment]
I fixed this specific error with https://github.com/mltframework/shotcut/commit/ef8541792482277810f2968c06bb3c2ac403a28c
However, Shotcut will still not build with Qt 5.6 because of webkitwidgets
