### PR TITLE
Fix some QT deprecation warnings

### PR DESCRIPTION
**Pull request by bmatherly**

### CODE REVIEW

**Comment by ddennedy** [comment]
When I did the Qt upgrade, I fixed many of these same deprecations while I was working with Qt 5.15. Then, I had to revert them because the macOS build is using version 5.12 to keep backwards compatibility with more macOS versions. This branch fails on macOS with Qt 5.12. We will update the minimum macOS and Qt version when the rest of Shotcut is ready for Qt 6, and this PR must wait until we branch to work on that.
```
5.12.9/clang_64/lib -o filedatedialog.o /Users/ddennedy/Projects/Shotcut/src/shotcut/src/dialogs/filedatedialog.cpp
In file included from /Users/ddennedy/Projects/Shotcut/src/shotcut/src/controllers/filtercontroller.cpp:19:
In file included from /Users/ddennedy/Projects/Shotcut/src/shotcut/src/controllers/filtercontroller.h:26:
/Users/ddennedy/Projects/Shotcut/src/shotcut/src/qmltypes/qmlmetadata.h:86:67: error: no matching constructor for initialization of 'QQmlListProperty<QmlKeyframesParameter>'
    QQmlListProperty<QmlKeyframesParameter> parameters() { return QQmlListProperty<QmlKeyframesParameter>(this, &m_parameters); }
                                                                  ^                                       ~~~~~~~~~~~~~~~~~~~
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtQml.framework/Headers/qqmllist.h:69:5: note: candidate constructor not viable: no known conversion from 'QList<QmlKeyframesParameter *> *' to 'QList<QmlKeyframesParameter *> &' for 2nd argument; remove &
    QQmlListProperty(QObject *o, QList<T *> &list)
    ^
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtQml.framework/Headers/qqmllist.h:56:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
class QQmlListProperty {
      ^
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtQml.framework/Headers/qqmllist.h:56:7: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtQml.framework/Headers/qqmllist.h:63:5: note: candidate constructor not viable: requires 0 arguments, but 2 were provided
    QQmlListProperty()
    ^
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtQml.framework/Headers/qqmllist.h:84:5: note: candidate constructor not viable: requires 4 arguments, but 2 were provided
    QQmlListProperty(QObject *o, void *d, CountFunction c, AtFunction t)
    ^
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtQml.framework/Headers/qqmllist.h:74:5: note: candidate constructor not viable: requires 6 arguments, but 2 were provided
    QQmlListProperty(QObject *o, void *d, AppendFunction a, CountFunction c, AtFunction t,
    ^
1 error generated.
make[1]: *** [filtercontroller.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from /Users/ddennedy/Projects/Shotcut/src/shotcut/src/docks/encodedock.cpp:30:
In file included from /Users/ddennedy/Projects/Shotcut/src/shotcut/src/qmltypes/qmlfilter.h:30:
/Users/ddennedy/Projects/Shotcut/src/shotcut/src/qmltypes/qmlmetadata.h:86:67: error: no matching constructor for initialization of 'QQmlListProperty<QmlKeyframesParameter>'
    QQmlListProperty<QmlKeyframesParameter> parameters() { return QQmlListProperty<QmlKeyframesParameter>(this, &m_parameters); }
                                                                  ^                                       ~~~~~~~~~~~~~~~~~~~
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtQml.framework/Headers/qqmllist.h:69:5: note: candidate constructor not viable: no known conversion from 'QList<QmlKeyframesParameter *> *' to 'QList<QmlKeyframesParameter *> &' for 2nd argument; remove &
    QQmlListProperty(QObject *o, QList<T *> &list)
    ^
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtQml.framework/Headers/qqmllist.h:56:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
class QQmlListProperty {
      ^
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtQml.framework/Headers/qqmllist.h:56:7: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtQml.framework/Headers/qqmllist.h:63:5: note: candidate constructor not viable: requires 0 arguments, but 2 were provided
    QQmlListProperty()
    ^
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtQml.framework/Headers/qqmllist.h:84:5: note: candidate constructor not viable: requires 4 arguments, but 2 were provided
    QQmlListProperty(QObject *o, void *d, CountFunction c, AtFunction t)
    ^
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtQml.framework/Headers/qqmllist.h:74:5: note: candidate constructor not viable: requires 6 arguments, but 2 were provided
    QQmlListProperty(QObject *o, void *d, AppendFunction a, CountFunction c, AtFunction t,
    ^
In file included from /Users/ddennedy/Projects/Shotcut/src/shotcut/src/mltcontroller.cpp:37:
In file included from /Users/ddennedy/Projects/Shotcut/src/shotcut/src/controllers/filtercontroller.h:26:
/Users/ddennedy/Projects/Shotcut/src/shotcut/src/qmltypes/qmlmetadata.h:86:67: error: no matching constructor for initialization of 'QQmlListProperty<QmlKeyframesParameter>'
    QQmlListProperty<QmlKeyframesParameter> parameters() { return QQmlListProperty<QmlKeyframesParameter>(this, &m_parameters); }
                                                                  ^                                       ~~~~~~~~~~~~~~~~~~~
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtQml.framework/Headers/qqmllist.h:69:5: note: candidate constructor not viable: no known conversion from 'QList<QmlKeyframesParameter *> *' to 'QList<QmlKeyframesParameter *> &' for 2nd argument; remove &
    QQmlListProperty(QObject *o, QList<T *> &list)
    ^
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtQml.framework/Headers/qqmllist.h:56:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
class QQmlListProperty {
      ^
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtQml.framework/Headers/qqmllist.h:56:7: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtQml.framework/Headers/qqmllist.h:63:5: note: candidate constructor not viable: requires 0 arguments, but 2 were provided
    QQmlListProperty()
    ^
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtQml.framework/Headers/qqmllist.h:84:5: note: candidate constructor not viable: requires 4 arguments, but 2 were provided
    QQmlListProperty(QObject *o, void *d, CountFunction c, AtFunction t)
    ^
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtQml.framework/Headers/qqmllist.h:74:5: note: candidate constructor not viable: requires 6 arguments, but 2 were provided
    QQmlListProperty(QObject *o, void *d, AppendFunction a, CountFunction c, AtFunction t,
    ^
In file included from /Users/ddennedy/Projects/Shotcut/src/shotcut/src/mainwindow.cpp:50:
In file included from /Users/ddennedy/Projects/Shotcut/src/shotcut/src/controllers/filtercontroller.h:26:
/Users/ddennedy/Projects/Shotcut/src/shotcut/src/qmltypes/qmlmetadata.h:86:67: error: no matching constructor for initialization of 'QQmlListProperty<QmlKeyframesParameter>'
    QQmlListProperty<QmlKeyframesParameter> parameters() { return QQmlListProperty<QmlKeyframesParameter>(this, &m_parameters); }
                                                                  ^                                       ~~~~~~~~~~~~~~~~~~~
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtQml.framework/Headers/qqmllist.h:69:5: note: candidate constructor not viable: no known conversion from 'QList<QmlKeyframesParameter *> *' to 'QList<QmlKeyframesParameter *> &' for 2nd argument; remove &
    QQmlListProperty(QObject *o, QList<T *> &list)
    ^
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtQml.framework/Headers/qqmllist.h:56:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
class QQmlListProperty {
      ^
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtQml.framework/Headers/qqmllist.h:56:7: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtQml.framework/Headers/qqmllist.h:63:5: note: candidate constructor not viable: requires 0 arguments, but 2 were provided
    QQmlListProperty()
    ^
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtQml.framework/Headers/qqmllist.h:84:5: note: candidate constructor not viable: requires 4 arguments, but 2 were provided
    QQmlListProperty(QObject *o, void *d, CountFunction c, AtFunction t)
    ^
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtQml.framework/Headers/qqmllist.h:74:5: note: candidate constructor not viable: requires 6 arguments, but 2 were provided
    QQmlListProperty(QObject *o, void *d, AppendFunction a, CountFunction c, AtFunction t,
    ^
1 error generated.
make[1]: *** [mltcontroller.o] Error 1
/Users/ddennedy/Projects/Shotcut/src/shotcut/src/docks/encodedock.cpp:934:9: error: no matching member function for call to 'setContent'
    dom.setContent(&xmlReader, false);
    ~~~~^~~~~~~~~~
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtXml.framework/Headers/qdom.h:338:10: note: candidate function not viable: no known conversion from 'QXmlStreamReader *' to 'const QByteArray' for 1st argument
    bool setContent(const QByteArray& text, bool namespaceProcessing, QString *errorMsg=nullptr, int *errorLine=nullptr, int *errorColumn=nullptr );
         ^
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtXml.framework/Headers/qdom.h:339:10: note: candidate function not viable: no known conversion from 'QXmlStreamReader *' to 'const QString' for 1st argument
    bool setContent(const QString& text, bool namespaceProcessing, QString *errorMsg=nullptr, int *errorLine=nullptr, int *errorColumn=nullptr );
         ^
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtXml.framework/Headers/qdom.h:340:10: note: candidate function not viable: no known conversion from 'QXmlStreamReader *' to 'QIODevice *' for 1st argument
    bool setContent(QIODevice* dev, bool namespaceProcessing, QString *errorMsg=nullptr, int *errorLine=nullptr, int *errorColumn=nullptr );
         ^
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtXml.framework/Headers/qdom.h:341:10: note: candidate function not viable: no known conversion from 'QXmlStreamReader *' to 'QXmlInputSource *' for 1st argument
    bool setContent(QXmlInputSource *source, bool namespaceProcessing, QString *errorMsg=nullptr, int *errorLine=nullptr, int *errorColumn=nullptr );
         ^
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtXml.framework/Headers/qdom.h:342:10: note: candidate function not viable: no known conversion from 'QXmlStreamReader *' to 'const QByteArray' for 1st argument
    bool setContent(const QByteArray& text, QString *errorMsg=nullptr, int *errorLine=nullptr, int *errorColumn=nullptr );
         ^
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtXml.framework/Headers/qdom.h:343:10: note: candidate function not viable: no known conversion from 'QXmlStreamReader *' to 'const QString' for 1st argument
    bool setContent(const QString& text, QString *errorMsg=nullptr, int *errorLine=nullptr, int *errorColumn=nullptr );
         ^
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtXml.framework/Headers/qdom.h:344:10: note: candidate function not viable: no known conversion from 'QXmlStreamReader *' to 'QIODevice *' for 1st argument
    bool setContent(QIODevice* dev, QString *errorMsg=nullptr, int *errorLine=nullptr, int *errorColumn=nullptr );
         ^
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtXml.framework/Headers/qdom.h:345:10: note: candidate function not viable: no known conversion from 'QXmlStreamReader *' to 'QXmlInputSource *' for 1st argument
    bool setContent(QXmlInputSource *source, QXmlReader *reader, QString *errorMsg=nullptr, int *errorLine=nullptr, int *errorColumn=nullptr );
         ^
/Users/ddennedy/Projects/Shotcut/src/shotcut/src/docks/encodedock.cpp:2032:90: error: no member named 'SkipEmptyParts' in namespace 'Qt'
            foreach (const QString& line, output.split(QRegularExpression("[\r\n]"), Qt::SkipEmptyParts))
                                                                                     ~~~~^
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtCore.framework/Headers/qglobal.h:1029:21: note: expanded from macro 'foreach'
#    define foreach Q_FOREACH
                    ^
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtCore.framework/Headers/qglobal.h:1018:58: note: expanded from macro 'Q_FOREACH'
for (auto _container_ = QtPrivate::qMakeForeachContainer(container); \
                                                         ^~~~~~~~~
In file included from /Users/ddennedy/Projects/Shotcut/src/shotcut/src/glwidget.cpp:33:
In file included from /Users/ddennedy/Projects/Shotcut/src/shotcut/src/qmltypes/qmlfilter.h:30:
/Users/ddennedy/Projects/Shotcut/src/shotcut/src/qmltypes/qmlmetadata.h:86:67: error: no matching constructor for initialization of 'QQmlListProperty<QmlKeyframesParameter>'
    QQmlListProperty<QmlKeyframesParameter> parameters() { return QQmlListProperty<QmlKeyframesParameter>(this, &m_parameters); }
                                                                  ^                                       ~~~~~~~~~~~~~~~~~~~
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtQml.framework/Headers/qqmllist.h:69:5: note: candidate constructor not viable: no known conversion from 'QList<QmlKeyframesParameter *> *' to 'QList<QmlKeyframesParameter *> &' for 2nd argument; remove &
    QQmlListProperty(QObject *o, QList<T *> &list)
    ^
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtQml.framework/Headers/qqmllist.h:56:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
class QQmlListProperty {
      ^
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtQml.framework/Headers/qqmllist.h:56:7: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtQml.framework/Headers/qqmllist.h:63:5: note: candidate constructor not viable: requires 0 arguments, but 2 were provided
    QQmlListProperty()
    ^
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtQml.framework/Headers/qqmllist.h:84:5: note: candidate constructor not viable: requires 4 arguments, but 2 were provided
    QQmlListProperty(QObject *o, void *d, CountFunction c, AtFunction t)
    ^
/Users/ddennedy/Qt/5.12.9/clang_64/lib/QtQml.framework/Headers/qqmllist.h:74:5: note: candidate constructor not viable: requires 6 arguments, but 2 were provided
    QQmlListProperty(QObject *o, void *d, AppendFunction a, CountFunction c, AtFunction t,
    ^
3 errors generated.
make[1]: *** [encodedock.o] Error 1
1 error generated.
make[1]: *** [glwidget.o] Error 1
1 error generated.
make[1]: *** [mainwindow.o] Error 1
make: *** [sub-src-make_first] Error 2
```

**Comment by ddennedy** [comment]
I am working on this in my own branch (local currently), and it is almost ready. This is obsolete now.
