### ISSUE TITLE
Not building with Qt 5.6

### ISSUE THREAD

**Issue by midyukov-anton** [mltframework/shotcut#215]
g++ -c -pipe -Wall -g -O2 -fPIC -DPIC -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DSHOTCUT_VERSION=\"16.04.03\" -D_REENTRANT -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_WEBKITWIDGETS_LIB -DQT_QUICKWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_QUICK_LIB -DQT_WEBKIT_LIB -DQT_MULTIMEDIA_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_QML_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CORE_LIB -I. -I../CuteLogger/include -I../mvcp -isystem /usr/include/mlt++ -isystem /usr/include/mlt -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtOpenGL -isystem /usr/include/qt5/QtPrintSupport -isystem /usr/include/qt5/QtWebKitWidgets -isystem /usr/include/qt5/QtQuickWidgets -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtQuick/5.6.0 -isystem /usr/include/qt5/QtQuick/5.6.0/QtQuick -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtWebKit -isystem /usr/include/qt5/QtMultimedia -isystem /usr/include/qt5/QtGui/5.6.0 -isystem /usr/include/qt5/QtGui/5.6.0/QtGui -isystem /usr/include/qt5/QtX11Extras -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtXml -isystem /usr/include/qt5/QtQml/5.6.0 -isystem /usr/include/qt5/QtQml/5.6.0/QtQml -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtWebSockets -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtCore/5.6.0 -isystem /usr/include/qt5/QtCore/5.6.0/QtCore -isystem /usr/include/qt5/QtCore -I. -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o scopecontroller.o controllers/scopecontroller.cpp
In file included from ./widgets/scopes/audioloudnessscopewidget.h:22:0,
                 from controllers/scopecontroller.cpp:19:
./widgets/scopes/scopewidget.h:87:10: error: 'void ScopeWidget::onNewFrame(const SharedFrame&)' marked 'final', but is not virtual
     void onNewFrame(const SharedFrame& frame) Q_DECL_FINAL;
          ^
./widgets/scopes/scopewidget.h:95:10: error: 'void ScopeWidget::requestRefresh()' marked 'final', but is not virtual
     void requestRefresh() Q_DECL_FINAL;
          ^
./widgets/scopes/scopewidget.h:118:22: error: 'void ScopeWidget::onRefreshThreadComplete()' marked 'final', but is not virtual
     Q_INVOKABLE void onRefreshThreadComplete() Q_DECL_FINAL;
                      ^
./widgets/scopes/scopewidget.h:119:10: error: 'void ScopeWidget::refreshInThread()' marked 'final', but is not virtual
     void refreshInThread() Q_DECL_FINAL;
          ^
In file included from docks/scopedock.h:22:0,
                 from docks/scopedock.cpp:19:
./widgets/scopes/scopewidget.h:87:10: error: 'void ScopeWidget::onNewFrame(const SharedFrame&)' marked 'final', but is not virtual
     void onNewFrame(const SharedFrame& frame) Q_DECL_FINAL;
          ^
./widgets/scopes/scopewidget.h:95:10: error: 'void ScopeWidget::requestRefresh()' marked 'final', but is not virtual
     void requestRefresh() Q_DECL_FINAL;
          ^
./widgets/scopes/scopewidget.h:118:22: error: 'void ScopeWidget::onRefreshThreadComplete()' marked 'final', but is not virtual
     Q_INVOKABLE void onRefreshThreadComplete() Q_DECL_FINAL;
                      ^
./widgets/scopes/scopewidget.h:119:10: error: 'void ScopeWidget::refreshInThread()' marked 'final', but is not virtual
     void refreshInThread() Q_DECL_FINAL;
          ^
make[1]: *** [scopecontroller.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [scopedock.o] Error 1
make[1]: Leaving directory `/usr/src/RPM/BUILD/shotcut-16.04/src'
make: *** [sub-src-make_first] Error 2

Full log building: http://git.altlinux.org/beehive/logs/Sisyphus-x86_64/latest/error/shotcut-16.03-alt1

**Comment by bmatherly** [comment]
Duplicate of https://github.com/mltframework/shotcut/issues/180

If you want to submit a patch that works with 5.6 and 5.5, I would be willing to take a look. But it can not break the official build script:
https://github.com/mltframework/shotcut/blob/master/scripts/build-shotcut.sh

**Comment by ddennedy** [comment]
These do seem like legitimate errors unrelated to Qt. Why are declare something is final when it is not even virtual? I think we should remove Q_DECL_FINAL on the methods in this header.

With respect to Qt 5.6, it removes the QtWebKit module, which we rely upon. It is not yet clear to me that we can actually do everything we need to do with the newer Qt WebEngine module. That certainly seems true for WebVfx but maybe also for the WYSIWYG HTML editor. I have not fully analyzed this, but I get that impression from Qt blog posts and their comments. Also, Shotcut is untested with that version. I have found that our intensive use Qt features does not hold up so well from one Qt 5 version to the next. IOW, we have had to make quite a bit of changes with each Qt version change we have adopted.

**Comment by bmatherly** [comment]
I think I was trying to use the final declaration as a form of self-documenting code to indicate which functions should be implemented by scopes and which functions can not be re-implemented by scopes. Someone could get really confused by re-implementing some of those functions and then accessing members from the wrong thread context. Maybe I'm paranoid.

I suppose we could solve the problem in two ways:
1) Remove the final declaration
2) Make the functions virtual

I would lean toward #2 because if someone found a reason to implement any of those functions, I would want to know about it so that I could assess their design strategy.

**Comment by itspec-ru** [comment]
OK
Thanks for the quick response

**Comment by bmatherly** [comment]
I fixed this specific error with https://github.com/mltframework/shotcut/commit/ef8541792482277810f2968c06bb3c2ac403a28c
However, Shotcut will still not build with Qt 5.6 because of webkitwidgets
