### ISSUE TITLE
build failed with Qt-5.6.0

### ISSUE THREAD

**Issue by itspec-ru** [mltframework/shotcut#241]
$git log | head -n 3
commit 404502f4ebe64ab61969f4afb59ab2472f1db3c2
Author: Brian Matherly <code@brianmatherly.com>
Date:   Wed May 11 23:43:26 2016 -0500

gcc --version
gcc (Gentoo 4.9.3 p1.3, pie-0.6.3) 4.9.3

After update qt to 5.6.0 I'm get error:

In file included from docks/scopedock.h:22:0,
                 from docks/scopedock.cpp:19:
./widgets/scopes/scopewidget.h:87:10: error: ‘void ScopeWidget::onNewFrame(const SharedFrame&)’ marked final, but is not virtual
     void onNewFrame(const SharedFrame& frame) Q_DECL_FINAL;
          ^
./widgets/scopes/scopewidget.h:95:10: error: ‘void ScopeWidget::requestRefresh()’ marked final, but is not virtual
     void requestRefresh() Q_DECL_FINAL;
          ^
In file included from docks/scopedock.h:22:0,
                 from docks/scopedock.cpp:19:
./widgets/scopes/scopewidget.h:118:10: error: ‘void ScopeWidget::onRefreshThreadComplete()’ marked final, but is not virtual
     Q_INVOKABLE void onRefreshThreadComplete() Q_DECL_FINAL;
          ^
./widgets/scopes/scopewidget.h:119:10: error: ‘void ScopeWidget::refreshInThread()’ marked final, but is not virtual
     void refreshInThread() Q_DECL_FINAL;
          ^
Makefile:2579: recipe for target 'scopedock.o' failed
make[1]: *** [scopedock.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from ./widgets/scopes/audioloudnessscopewidget.h:22:0,
                 from controllers/scopecontroller.cpp:19:
./widgets/scopes/scopewidget.h:87:10: error: ‘void ScopeWidget::onNewFrame(const SharedFrame&)’ marked final, but is not virtual
     void onNewFrame(const SharedFrame& frame) Q_DECL_FINAL;
          ^
./widgets/scopes/scopewidget.h:95:10: error: ‘void ScopeWidget::requestRefresh()’ marked final, but is not virtual
     void requestRefresh() Q_DECL_FINAL;
          ^
In file included from ./widgets/scopes/audioloudnessscopewidget.h:22:0,
                 from controllers/scopecontroller.cpp:19:
./widgets/scopes/scopewidget.h:118:10: error: ‘void ScopeWidget::onRefreshThreadComplete()’ marked final, but is not virtual
     Q_INVOKABLE void onRefreshThreadComplete() Q_DECL_FINAL;
          ^
./widgets/scopes/scopewidget.h:119:10: error: ‘void ScopeWidget::refreshInThread()’ marked final, but is not virtual
     void refreshInThread() Q_DECL_FINAL;
          ^
Makefile:2594: recipe for target 'scopecontroller.o' failed
make[1]: *** [scopecontroller.o] Error 1
In file included from widgets/scopes/scopewidget.cpp:19:0:
widgets/scopes/scopewidget.h:87:10: error: ‘void ScopeWidget::onNewFrame(const SharedFrame&)’ marked final, but is not virtual
     void onNewFrame(const SharedFrame& frame) Q_DECL_FINAL;
          ^
widgets/scopes/scopewidget.h:95:10: error: ‘void ScopeWidget::requestRefresh()’ marked final, but is not virtual
     void requestRefresh() Q_DECL_FINAL;
          ^
In file included from widgets/scopes/scopewidget.cpp:19:0:
widgets/scopes/scopewidget.h:118:10: error: ‘void ScopeWidget::onRefreshThreadComplete()’ marked final, but is not virtual
     Q_INVOKABLE void onRefreshThreadComplete() Q_DECL_FINAL;
          ^
widgets/scopes/scopewidget.h:119:10: error: ‘void ScopeWidget::refreshInThread()’ marked final, but is not virtual
     void refreshInThread() Q_DECL_FINAL;
          ^
Makefile:2601: recipe for target 'scopewidget.o' failed
make[1]: *** [scopewidget.o] Error 1
In file included from widgets/scopes/audioloudnessscopewidget.h:22:0,
                 from widgets/scopes/audioloudnessscopewidget.cpp:19:
widgets/scopes/scopewidget.h:87:10: error: ‘void ScopeWidget::onNewFrame(const SharedFrame&)’ marked final, but is not virtual
     void onNewFrame(const SharedFrame& frame) Q_DECL_FINAL;
          ^
widgets/scopes/scopewidget.h:95:10: error: ‘void ScopeWidget::requestRefresh()’ marked final, but is not virtual
     void requestRefresh() Q_DECL_FINAL;
          ^
In file included from widgets/scopes/audioloudnessscopewidget.h:22:0,
                 from widgets/scopes/audioloudnessscopewidget.cpp:19:
widgets/scopes/scopewidget.h:118:10: error: ‘void ScopeWidget::onRefreshThreadComplete()’ marked final, but is not virtual
     Q_INVOKABLE void onRefreshThreadComplete() Q_DECL_FINAL;
          ^
widgets/scopes/scopewidget.h:119:10: error: ‘void ScopeWidget::refreshInThread()’ marked final, but is not virtual
     void refreshInThread() Q_DECL_FINAL;
          ^
Makefile:2613: recipe for target 'audioloudnessscopewidget.o' failed
make[1]: *** [audioloudnessscopewidget.o] Error 1
make[1]: Leaving directory '/var/tmp/portage/media-video/shotcut-9999/work/shotcut-9999/src'
Makefile:95: recipe for target 'sub-src-make_first' failed
make: *** [sub-src-make_first] Error 2

**Comment by bmatherly** [comment]
Duplicate of https://github.com/mltframework/shotcut/issues/180 and https://github.com/mltframework/shotcut/issues/215

**Comment by itspec-ru** [comment]
OK
Thanks for the quick response

**Comment by bmatherly** [comment]
I fixed this specific error with https://github.com/mltframework/shotcut/commit/ef8541792482277810f2968c06bb3c2ac403a28c
However, Shotcut will still not build with Qt 5.6 because of webkitwidgets

**Comment by itspec-ru** [comment]
Thanks for the fixes. I built shotcut in Gentoo Linux using QT 5.6. I had not any errors. Everything seems to work correctly.
These packages related to QT installed on my system
linguist-tools-5.6.0
qtchooser-0_p20151008
qtconcurrent-5.6.0
qtcore-5.6.0
qtdbus-5.6.0
qtdeclarative-5.6.0
qtgraphicaleffects-5.6.0
qtgui-5.6.0-r1
qtlockedfile-2.4.1_p20150629
qtmultimedia-5.6.0
qtnetwork-5.6.0
qtopengl-5.6.0
qtpositioning-5.6.0-r1
qtprintsupport-5.6.0
qtquick1-5.6.0
qtquickcontrols-5.6.0
qtscript-5.6.0
qtsensors-5.6.0
qtsingleapplication-2.6.1_p20150629
qtsql-5.6.0
qtsvg-5.6.0
qttest-5.6.0
qtwebchannel-5.6.0
qtwebengine-5.6.0
qtwebkit-5.6.0
qtwebsockets-5.6.0-r2
qtwidgets-5.6.0
qtx11extras-5.6.0
qtxml-5.6.0
qtxmlpatterns-5.6.0

**Comment by bmatherly** [comment]
Ok. I see what is going on here. webkit is still part of the Qt source. But they dropped support for it and they exclude it from the official Qt binaries starting with 5.6. Here at Shotcut, we are going to stick with supporting Qt5.5 while we figure out a solution for webkit/webengine. In the mean time, if you (or anyone else using your build) experience any issues, we will ask that you first reproduce the issue with the official Shotcut build before reporting it.
