### ISSUE TITLE
shotcut-18.05 doesn’t build with MLT 6.6.0

### ISSUE THREAD

**Issue by martinkg** [mltframework/shotcut#550]
Fedora 28 doesn't compile with MLT 6.6.0

```
widgets/avformatproducerwidget.cpp: In member function 'void AvformatProducerWidget::onFrameDisplayed(const SharedFrame&)':
widgets/avformatproducerwidget.cpp:261:62: error: 'mlt_channel_layout_default' was not declared in this scope
                 const char* layout = mlt_channel_layout_name(mlt_channel_layout_default(channels));
                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
widgets/avformatproducerwidget.cpp:261:38: error: 'mlt_channel_layout_name' was not declared in this scope
                 const char* layout = mlt_channel_layout_name(mlt_channel_layout_default(channels));
                                      ^~~~~~~~~~~~~~~~~~~~~~~
widgets/avformatproducerwidget.cpp:261:38: note: suggested alternative: 'mlt_cache_put_frame'
                 const char* layout = mlt_channel_layout_name(mlt_channel_layout_default(channels));
                                      ^~~~~~~~~~~~~~~~~~~~~~~
                                      mlt_cache_put_frame
make[1]: *** [Makefile:2613: avformatproducerwidget.o] Error 1
make[1]: Leaving directory '/home/martin/rpmbuild/BUILD/shotcut-18.05/src'
make[1]: *** Waiting for unfinished jobs....
make[1]: Entering directory '/home/martin/rpmbuild/BUILD/shotcut-18.05/src'
```
when will shotcut compile with MLT 6.6.0, with a special version of shotcut ?

**Comment by ddennedy** [comment]
> when will shotcut compile with MLT 6.6.0, with a special version of shotcut ?

Shotcut 18.03.06 is the last version that compiles with MLT v6.6.0. It is typical that Shotcut requires MLT git master as I lead on both, and mutually use one project to drive the other. The versions used for official builds are prescribed in the src/build-shotcut.sh script nighly build script, and the mostly monthly releases are plucked from the nightly builds. I can release a new version of MLT soon, but I will give a couple more days to see if any critical new bug appeared that needs fixing.

**Comment by martinkg** [comment]
Thanks for the info, i will wait until a new version of MLT is released.

**Comment by ddennedy** [comment]
MLT 6.8.0 is released:
https://github.com/mltframework/mlt/releases/tag/v6.8.0
